apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::023xcxc34523232:role/dev-nodegroup-ondemandwork-nodeinstancerole
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::023xcxc3452323:user/krishna_rudraraju
      username: krishna_rudraraju
      groups:
        - system:masters
    - userarn: arn:aws:iam::023xcxc3452323:user/dev-ops
      username: dev-ops
      groups:
        - system:masters
    - userarn: arn:aws:iam::023xcxc3452323:user/jenkins-user-ec
      username: jenkins-user-ec
      groups:
        - system:masters
